"""
ASR module configuration — the MultiMed-ST whisper candidates and eval paths.

This module is the ONLY place that introduces torch/transformers into the project. It is kept
isolated from the no-torch RAG/embedding core: nothing under src/rag, src/embedding, src/fhir or
src/scoring imports it, and the offline tests never load a model. See docs/RAG_REPORT.md for the
bake-off decision that fills ASR_MODEL.
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))  # src/ on sys.path
from paths import CHUNKS_DIR, DATA_DIR  # noqa: E402

# Whisper expects 16 kHz mono audio.
ASR_SAMPLE_RATE = 16000

# The chosen model. It is a whisper-small fine-tune whose *weights* live in a checkpoint subfolder
# of the HuggingFace repo while the *processor* (tokenizer + feature extractor) sits at the parent
# folder — the two load from different paths. We no longer run it through transformers at inference:
# the production runtime is CTranslate2 (faster-whisper), with weights converted to int8_float16
# (see ASR_CT2_DIR / src/asr/eval/convert_ct2.py). The HF subfolders below are kept ONLY so the
# converter can re-stage and re-quantize from the cached weights; nothing loads torch at serve time.
ASR_REPO = "leduckhai/MultiMed-ST"

# CTranslate2 model artifacts (generated by convert_ct2.py; gitignored under data/asr_ct2/).
ASR_CT2_DIR = DATA_DIR / "asr_ct2"

ASR_MODELS: dict[str, dict] = {
    "whisper-multilingual": {
        "label": "MultiMed-ST whisper-small (multilingual) · CTranslate2 int8_float16",
        "model_subfolder": "asr/whisper-small-multilingual/checkpoint",   # converter source (weights)
        "processor_subfolder": "asr/whisper-small-multilingual",          # converter source (tokenizer)
        "ct2_dir": ASR_CT2_DIR / "whisper-multilingual-int8_float16",     # served by faster-whisper
    },
}

# Chosen by the bake-off (chunks/asr_bakeoff_report.md, 2026-06-18): the multilingual model beat
# the VN monolingual on BOTH drug-name accuracy (30.6% vs 17.7%) and WER (0.280 vs 0.465) on the
# curated VN drug-name set — it handles the English drug names (code-switching) better. The losing
# VN monolingual entry was dropped when we migrated to CT2. PROVISIONAL per project discipline: n is
# small and TTS is clean (drug accuracy is a deflated lower bound); confirm on real bedside audio.
ASR_MODEL: str = "whisper-multilingual"

# Decoder settings — single source of truth for the bake-off harness and the live push-to-talk
# endpoint, so production gets exactly what the experiments validated. These are faster-whisper
# (CTranslate2) generation params:
#   - compute_type "int8_float16": int8 weights + fp16 compute. Validated byte-equal on the safety
#     KPI — recoverable recall 93.9% identical to the fp16 transformers baseline, ~2x faster decode,
#     ~half the VRAM (docs/ASR_CT2_MIGRATION.md). The model is converted at this precision.
#   - beam_size=1 (greedy): the decoding sweep tested beam search, no_repeat_ngram, and Whisper's
#     temperature fallback — ALL RAISED WER and, worse, LOWERED drug recoverability (beam smooths the
#     phonetic garble the matcher relies on to recover English drug names). Greedy stays best on
#     every axis. Don't re-add these without re-running the sweep (docs/ASR_REPORT.md §4.6).
#   - temperature=0.0: no fallback retries (the sweep rejected them).
DECODE: dict = {
    "compute_type": "int8_float16",
    "beam_size": 1,
    "temperature": 0.0,
}

# Eval artifacts.
ASR_TEST_DIR = DATA_DIR / "asr_test"               # generated TTS audio (gitignored)
ASR_REPORT_FILE = CHUNKS_DIR / "asr_bakeoff_report.md"
ASR_REPORT_JSON = CHUNKS_DIR / "asr_bakeoff_report.json"

# Vietnamese TTS variants for the curated drug-name test set. We use gTTS (Google) because the
# edge-tts neural voices currently fail auth (NoAudioReceived) — gTTS is reliable, no API key.
# gTTS has one VN voice, so the two "variants" differ by speaking rate (normal vs slow); this is a
# mild robustness check, not true speaker diversity (stated as a caveat in the report).
TTS_VARIANTS = {"normal": {"slow": False}, "slow": {"slow": True}}
